name: Testes de Api 

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do projeto
      uses: actions/checkout@v1
    - name: Setup do Node.js
      uses: actions/setup-node@v2
    - name: Instalação das dependências de produção
      run: npm ci 
    - name: Execução dos testes
      run: npm run cypress:run